apiVersion: v1
kind: Service
metadata:
  labels:
    app: task1a
  name: task1a
spec:
  selector:
    app: task1a
  type: ClusterIP
  ports:
    - name: http
      port: 8585
      protocol: TCP
      targetPort: http